### ISSUE TITLE
getting this error on order detail page with debug

### ISSUE THREAD

**Issue by IKOMSDZE** [nikolays93/woocommerce-ru-city-rate-shipping#1]
` Fatal error: Uncaught Error: Call to a member function get_billing_state() on null in /home/evelineg/site.ge/wp-content/plugins/woocommerce-city-rate-shipping-master/city-rate-shipping.php:125 Stack trace: #0 /home/evelineg/site.ge/wp-includes/class-wp-hook.php(287): customize_checkout_city_field(Array) #1 /home/evelineg/site.ge/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #2 /home/evelineg/site.ge/wp-content/plugins/woocommerce/includes/class-wc-countries.php(737): apply_filters('woocommerce_def...', Array) #3 /home/evelineg/site.ge/wp-content/plugins/woocommerce/includes/class-wc-countries.php(1362): WC_Countries->get_default_address_fields() #4 /home/evelineg/site.ge/wp-content/plugins/woo-checkout-field-editor-pro/classes/class-thwcfd-utils.php(117): WC_Countries->get_address_fields('GE', 'shipping_') #5 /home/evelineg/site.ge/wp-content/plugins/woo-checkout-field-editor-pro/classes/class-thwcfd-settings-general.php(602): THWCFD_Utils::get_fields('shipping in /home/evelineg/site.ge/wp-content/plugins/woocommerce-city-rate-shipping-master/city-rate-shipping.php on line 125
`

**Comment by sukhikh18** [comment]
Oh.. so oldest prototype. I will try check(fix) it on the week for you.

**Comment by IKOMSDZE** [comment]
thaank you a lot
